### ISSUE TITLE
Install does not catch dependency `wrapt`

### ISSUE THREAD

**Issue by xkortex** [deepmind/sonnet#115]
`pip3 install dm-sonnet=1.27.0` leaves `wrapt` as a missing dependency. Installing wrapt fixes it, just need to add this to requirements. 

Traceback (most recent call last):
  
```
  File "GIT_DIR/muh_file.py", line 28, in <module>
    import sonnet as snt
  File "VIRTUAL_ENV/lib/python3.6/site-packages/sonnet/__init__.py", line 68, in <module>
    from sonnet.python.modules import experimental
  File "VIRTUAL_ENV/lib/python3.6/site-packages/sonnet/python/modules/experimental.py", line 26, in <module>
    from sonnet.python.modules import util
  File "VIRTUAL_ENV/lib/python3.6/site-packages/sonnet/python/modules/util.py", line 32, in <module>
    import wrapt
ModuleNotFoundError: No module named 'wrapt'
```

**Comment by malcolmreynolds** [comment]
Thanks for the spot - this will be fixed in the next public version.
