### ISSUE TITLE
getting this error after installing sonnet..ubuntu 18.04

### ISSUE THREAD

**Issue by DSOCT18** [deepmind/sonnet#132]
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.__version__)
1.13.1
>>> import sonnet as snt
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sonnet/__init__.py", line 47, in _ensure_dependency_available_at_version
    pkg = importlib.import_module(package_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tensorflow_probability'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/sonnet/__init__.py", line 64, in <module>
    _ensure_dependency_available_at_version('tensorflow_probability', '0.4.0')
  File "/usr/local/lib/python3.6/dist-packages/sonnet/__init__.py", line 54, in _ensure_dependency_available_at_version
    package_name, min_version, pip_name, pip_name))
SystemError: Sonnet requires tensorflow_probability (minimum version 0.4.0) to be installed. If using pip, run `pip install tensorflow-probability` or `pip install tensorflow-probability-gpu`
>>> 

i tried changing all the packages as said in the error messages but the problem still persists.
plz help if anybody had encountered this problem before.
Thank You.

**Comment by DSOCT18** [comment]
solved the problem...
no need to make an extra tmp/sonnet as it is alread present in bazel-bin/sonnet/tmp/sonnet.
the whl file will be created over the above path..
and then pip installing it will download dm-sonnet as well as tensorflow-probability as per the required version on its own.
