### ISSUE TITLE
ImportError: cannot import name 'ContextManager'

### ISSUE THREAD

**Issue by songjd** [deepmind/sonnet#151]
~pip list:
tensorflow-gpu             2.0.0      
tensorflow-probability     0.8.0 
dm-sonnet                  2.0.0b0 
wrapt                      1.11.1
six                        1.13.0 
absl-py                    0.8.1
tabulate                   0.8.5 
gast                       0.2.2

python 3.5.2

Traceback (most recent call last):
  File "train_xxx.py", line 31, in <module>
    import sonnet as snt
  File "/xxx/lib/python3.5/site-packages/sonnet/__init__.py", line 24, in <module>
    from sonnet import mixed_precision
  File "/xxx/lib/python3.5/site-packages/sonnet/mixed_precision.py", line 22, in <module>
    from sonnet.src.mixed_precision import disable
  File "/xxx/lib/python3.5/site-packages/sonnet/src/mixed_precision.py", line 25, in <module>
    from sonnet.src import custom_getter
  File "/xxx/lib/python3.5/site-packages/sonnet/src/custom_getter.py", line 25, in <module>
    from typing import Any, Callable, ContextManager, Iterable, Optional, Type
ImportError: cannot import name 'ContextManager'

**Comment by songjd** [comment]
I found the reason:

Other ones perhaps worth adding in:
    typing.Collection -- added in 3.6
    typing.Deque -- added in 3.6.1
    typing.ContextManager -- **added in 3.6**
    typing.Counter -- added in 3.6.1
    typing.ChainMap -- added in 3.6.1
    typing.AsyncGenerator -- added in 3.5.4
    typing.ClassVar -- added in 3.5.3
