### ISSUE TITLE
Running rnn_shakespeare.py triggers an Attribute Error on python 3.6.1

### ISSUE THREAD

**Issue by kustom666** [deepmind/sonnet#21]
As stated in the title, running the example rnn_shakespeare.py example triggers an attribute error types has no attribute StringTypes, eg:

`Traceback (most recent call last):
  File "shake.py", line 309, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "shake.py", line 305, in main
    reduce_learning_rate_interval=FLAGS.reduce_learning_rate_interval)
  File "shake.py", line 180, in train
    name="shake_train")
  File "/usr/local/lib/python3.6/site-packages/sonnet/examples/dataset_shakespeare.py", line 111, in __init__
    super(TinyShakespeareDataset, self).__init__(name=name)
  File "/usr/local/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 118, in __init__
    if not isinstance(name, types.StringTypes):
AttributeError: module 'types' has no attribute 'StringTypes'` 

This is most likely due to the fact that StringTypes was deprecated, and then later removed from python3

**Comment by malcolmreynolds** [comment]
As stated in the Readme, Python 3 is currently not support. There is a [pending PR](https://github.com/deepmind/sonnet/pull/10)  adding this support, we hope to have it integrated soon.

**Comment by diegolascasas** [comment]
Commit https://github.com/deepmind/sonnet/commit/578e3360741891428ea51c36741bbabc82265942 should add Python 3 support. I am closing this issue, but please reopen it if the problem persists.
