### ISSUE TITLE
Sonnet and pyinstaller

### ISSUE THREAD

**Issue by dmagee** [deepmind/sonnet#222]
Sonnet doesn't seem to work with pyinstaller. This can be reproduced with a very simple example as below:

```
import sonnet
print("Hello world")
```
I used a spec file:

```
# -*- mode: python ; coding: utf-8 -*-

# The following fixes a different pyinstaller issue due to recursion
import sys
sys.setrecursionlimit(5000)

block_cipher = None


a = Analysis(['pi_test.py'],
             pathex=['c:\\Software\\ICServer\\ICServer-src\\Python\\GraphNet\\minimal_pyinstaller_test'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='pi_test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='pi_test')
```

The error is:

```
2021-11-08 19:42:43.507236: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Traceback (most recent call last):
  File "site-packages\tensorflow\python\autograph\pyct\parser.py", line 150, in parse_entity
  File "site-packages\tensorflow\python\autograph\pyct\inspect_utils.py", line 147, in getimmediatesource
  File "inspect.py", line 798, in findsource
OSError: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\tensorflow\python\autograph\impl\api.py", line 749, in to_graph
  File "site-packages\tensorflow\python\autograph\impl\api.py", line 284, in _convert_actual
  File "site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 286, in transform
  File "site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 470, in transform_function
  File "site-packages\tensorflow\python\autograph\pyct\transpiler.py", line 346, in transform_function
  File "site-packages\tensorflow\python\autograph\pyct\parser.py", line 152, in parse_entity
ValueError: Unable to locate the source code of <function BaseBatchNorm.__call__ at 0x000002BF2C3C84C0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Software\ICServer\ICServer-src\Python\GraphNet\minimal_pyinstaller_test2\pi_test.py", line 1, in <module>
    import sonnet
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sonnet\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sonnet\distribute.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sonnet\src\distribute\batch_norm.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sonnet\src\batch_norm.py", line 34, in <module>
  File "site-packages\sonnet\src\batch_norm.py", line 132, in BaseBatchNorm
  File "site-packages\sonnet\src\utils.py", line 180, in smart_autograph
  File "site-packages\tensorflow\python\autograph\impl\api.py", line 752, in to_graph
tensorflow.python.autograph.impl.api.ConversionError: converting <function BaseBatchNorm.__call__ at 0x000002BF2C3C84C0>: ValueError: Unable to locate the source code of <function BaseBatchNorm.__call__ at 0x000002BF2C3C84C0>. Note that functions defined in certain environments, like the interactive Python shell do not expose their source code. If that is the case, you should to define them in a .py source file. If you are certain the code is graph-compatible, wrap the call using @tf.autograph.do_not_convert. Original error: could not get source code
```
The code works fine within the python interpreter, but within pyinstaller it seems to have trouble.

**Comment by tomhennigan** [comment]
Hi @dmagee, Sonnet makes use of Autograph in TensorFlow 2. It looks like TensorFlow Autograph (which requires being able to locate the Python source code for a given function to transpile it) is not compatible with the way pyinstaller is re-packaging Python libraries (such as Sonnet) that you depend on. I would suggest raising this as a bug on [TensorFlow](https://github.com/tensorflow/tensorflow/issues), this is not a bug the Sonnet authors can fix.

**Comment by dmagee** [comment]
For anyone with the same issue, you need the tensorflow hook as detailed in discussion here:

https://discuss.tensorflow.org/t/pyinstaller-tensorflow-sonnet/5835/5

It looks like some parts of tensorflow used by sonnet were not being packaged without this.
