### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by jcformanek** [deepmind/sonnet#226]
Hi, I am trying to use sonnet in a project. But I am getting the following error and don't know how to get aeound it. I would appreciate any help. 

````
2021-12-11T15:44:17.052298171Z Traceback (most recent call last):
2021-12-11T15:44:17.052337896Z   File "recurrent_agent.py", line 5, in <module>
2021-12-11T15:44:17.052345579Z     from sonnet import LSTM, Linear, DeepRNN, nets
2021-12-11T15:44:17.052350864Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/__init__.py", line 21, in <module>
2021-12-11T15:44:17.052356498Z     from sonnet import distribute
2021-12-11T15:44:17.052363196Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/distribute.py", line 21, in <module>
2021-12-11T15:44:17.052369514Z     from sonnet.src.distribute.batch_norm import CrossReplicaBatchNorm
2021-12-11T15:44:17.05237608Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/src/distribute/batch_norm.py", line 22, in <module>
2021-12-11T15:44:17.052383032Z     from sonnet.src import batch_norm
2021-12-11T15:44:17.052389323Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/src/batch_norm.py", line 34, in <module>
2021-12-11T15:44:17.052395593Z     class BaseBatchNorm(base.Module):
2021-12-11T15:44:17.052401251Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/src/batch_norm.py", line 132, in BaseBatchNorm
2021-12-11T15:44:17.052407672Z     def __call__(self,
2021-12-11T15:44:17.052451107Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/sonnet/src/utils.py", line 180, in smart_autograph
2021-12-11T15:44:17.0524592Z     f_autograph = tf.autograph.to_graph(f)
2021-12-11T15:44:17.052465501Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 774, in to_graph
2021-12-11T15:44:17.052472077Z     return autograph_artifact(_convert_actual(entity, program_ctx))
2021-12-11T15:44:17.05247823Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 274, in _convert_actual
2021-12-11T15:44:17.05248368Z     transformed, module, source_map = _TRANSPILER.transform(entity, program_ctx)
2021-12-11T15:44:17.052488903Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 286, in transform
2021-12-11T15:44:17.052494215Z     return self.transform_function(obj, user_context)
2021-12-11T15:44:17.05251413Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 490, in transform_function
2021-12-11T15:44:17.052519758Z     factory.create(
2021-12-11T15:44:17.052524489Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/transpiler.py", line 183, in create
2021-12-11T15:44:17.052529498Z     module, _, source_map = loader.load_ast(
2021-12-11T15:44:17.052537411Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/loader.py", line 99, in load_ast
2021-12-11T15:44:17.052542886Z     source_map = origin_info.create_source_map(nodes, source, module.__file__)
2021-12-11T15:44:17.052548014Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/origin_info.py", line 106, in create_source_map
2021-12-11T15:44:17.052553482Z     resolve(node, code, filepath, node.lineno, node.col_offset)
2021-12-11T15:44:17.052558575Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/origin_info.py", line 268, in resolve
2021-12-11T15:44:17.052564166Z     visitor.visit(node)
2021-12-11T15:44:17.052569042Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/origin_info.py", line 220, in visit
2021-12-11T15:44:17.052574695Z     self.generic_visit(node)
2021-12-11T15:44:17.052580016Z   File "/srv/conda/envs/notebook/lib/python3.8/ast.py", line 368, in generic_visit
2021-12-11T15:44:17.05259381Z     self.visit(item)
2021-12-11T15:44:17.052598735Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/origin_info.py", line 219, in visit
2021-12-11T15:44:17.052604397Z     self._attach_origin_info(node)
2021-12-11T15:44:17.052609559Z   File "/srv/conda/envs/notebook/lib/python3.8/site-packages/tensorflow/python/autograph/pyct/origin_info.py", line 203, in _attach_origin_info
2021-12-11T15:44:17.052614992Z     source_code_line = self._source_lines[node.lineno - 1]
2021-12-11T15:44:17.052620268Z TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by tomhennigan** [comment]
HI @jcformanek , this looks like a bug in TensorFlow's autograph feature. Sonnet uses autograph to enable us to write code with simple, easy to understand syntax that works equivalently in eager mode or graph mode.

Please ensure you're using the latest version of TensorFlow and see if the bug re-occurs. If the bug still exists after upgrading then [file a bug on their repo](https://github.com/tensorflow/tensorflow/issues) with instructions on how to reproduce the issue.

One thing we can potentially do in Sonnet to workaround this issue is to make our use of autograph lazier. I'll try that in #227 and once that has merged you can install the very latest version of Sonnet (which will include my fix) using:

```bash
$ pip install git+https://github.com/deepmind/sonnet
```

This will defer our use of autograph until you use a feature that requires it. Perhaps you will be lucky and the features you want from Sonnet will not require Sonnet to use autograph. If not you'll need to wait for the TF bug to get fixed after you file it.

**Comment by jcformanek** [comment]
Hi @tomhennigan. Thanks so much for the response. I switched to the latest version of Tensorflow and that seems to have fixed my problem.
