### ISSUE TITLE
Is there a convenient way to put variables of Sonnet module into specific collections?

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#69]
Dear engineers at Deepmind, in some situation I need to train a model, which has two targets, but the targets share part of the graph. The problem is if I am intended to compute the gradients for one target, since the incomplete information, the computation will fail. It can be demonstrated with the following code:

```
import numpy as np
import tensorflow as tf
import sonnet as snt

# common part shared by two targets
class CommonPart(snt.AbstractModule):
    def __init__(self, name = "common_part"):
        super(CommonPart, self).__init__(name = name)
        with self._enter_variable_scope():
            self._conv = snt.Conv2D(4, [3, 3])

    def _build(self, inputs):
        return self._conv(inputs)

# one target with specific output 1
class Output1(snt.AbstractModule):
    def __init__(self, output_size, name = "output1"):
        super(Output1, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# another target with specific output 2
class Output2(snt.AbstractModule):
    def __init__(self, output_size, name = "output2"):
        super(Output2, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# t1 is input for target1
t1 = tf.truncated_normal([1, 5, 5, 1])

# t2 is input for target 2
t2 = tf.truncated_normal([1, 5, 5, 1])

# l1 is ground truth label for target 1
l1 = tf.constant([[1, 0]])

# l2 is ground truth label for target 2
l2 = tf.constant([[0, 1, 0, 0]])

opt = tf.train.AdamOptimizer(0.01)

# we create the model, the two-head monster
common_part = CommonPart()
output1 = Output1(2)
output2 = Output2(4)

# feed-forward computation
i1 = common_part(t1)
i2 = common_part(t2)

o1 = output1(snt.BatchFlatten()(i1))
o2 = output2(snt.BatchFlatten()(i2))

# losses for separated targets
l1 = tf.nn.softmax_cross_entropy_with_logits(labels = l1, logits = o1)
l2 = tf.nn.softmax_cross_entropy_with_logits(labels = l2, logits = o2)

# neither of the following computation will be succeded
# due to the incomplete information
g1 = opt.compute_gradients(l1)
g2 = opt.compute_gradients(l2)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    g1_val, g2_val = sess.run([g1, g2])

    print(g1_val)

```
 
Sincerely hope our dear engineers at Deepmind will look into it and give some suggestions.

**Comment by malcolmreynolds** [comment]
@mingyr sorry, I'm not quite sure I follow. When I run your code both the compute_gradients lines execute fine - by default they get the gradients with respect to all variables, so there are some `None` returns due to the gradients with respect to variables in output1 not having any contribution to loss2, and vice versa. One option is to give compute_gradients a list of the variables to differentiate with respect to, by calling `get_variables` on common_part and the relevant output module. You could also just add the two losses together at the end and differentiate that, although you may not always want to provide data to both inputs.

If you want to put variables in specific collections, you could use a custom_getter in the variable_scope within which your modules are declared. I don't think it's necessary in this case though.

Apologies if I've misunderstood the problem - please let me know if the .get_variables suggestion works.

**Comment by mingyr** [comment]
@malcolmreynolds Really? Could you please tell me the version of TensorFlow and Sonnet when you run the code? I could fully understand the None output, but on the latest version it just stop working:

```
(tensorflow)[yuming@cibci2 working-files]$ python 45.py
2017-10-27 23:08:12.324778: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Found device 0 with properties:
name: Quadro P5000 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:03:00.0
totalMemory: 15.89GiB freeMemory: 15.65GiB
2017-10-27 23:08:12.491193: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1031] Found device 1 with properties:
name: Quadro P5000 major: 6 minor: 1 memoryClockRate(GHz): 1.7335
pciBusID: 0000:82:00.0
totalMemory: 15.89GiB freeMemory: 15.78GiB
2017-10-27 23:08:12.491302: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1046] Device peer to peer matrix
2017-10-27 23:08:12.491322: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1052] DMA: 0 1
2017-10-27 23:08:12.491327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1062] 0:   Y N
2017-10-27 23:08:12.491331: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1062] 1:   N Y
2017-10-27 23:08:12.491342: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Quadro P5000, pci bus id: 0000:03:00.0, compute capability: 6.1)
2017-10-27 23:08:12.491347: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1121] Creating TensorFlow device (/device:GPU:1) -> (device: 1, name: Quadro P5000, pci bus id: 0000:82:00.0, compute capability: 6.1)
Traceback (most recent call last):
  File "45.py", line 73, in <module>
    g1_val, g2_val = sess.run([g1, g2])
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1105, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 414, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 234, in for_fetch
    return _ListFetchMapper(fetch)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 341, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 231, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <type 'NoneType'>
(tensorflow)[yuming@cibci2 working-files]$

```

The version I currently used:

```
(tensorflow)[yuming@cibci2 working-files]$ pip list
dm-sonnet-gpu (1.13)
tensorflow (1.4.0rc0)

```

**Comment by malcolmreynolds** [comment]
@mingyr the compute_gradients call executes fine, but you are then requesting some of these None values from session.run, which causes the error you see. If you remove the `(None, variable)` elements from the result of compute_gradients the whole thing should run. Replace the last part with:

```
g1 = [(grad, var) for grad, var in opt.compute_gradients(l1)
      if grad is not None]
g2 = [(grad, var) for grad, var in opt.compute_gradients(l2)
      if grad is not None]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    g1_val, g2_val = sess.run([g1, g2])

    print(g1_val)
```

**Comment by mingyr** [comment]
@malcolmreynolds : I am sincerely appreciating your quick respond. However, probably I should first inspect it is a true problem or not by using tfdbg, but I really appreciate your dedication. I will keep you updated for the following part later. I got a terrible network connection to the cluster node which resides in the campus IDC.
Have a nice weekend.

**Comment by mingyr** [comment]
@malcolmreynolds Yes, I confirmed it works with get_variables, and I compared the outputs with WinMerge and they are identical. Please refer to the following code:

```
import numpy as np
import tensorflow as tf
import sonnet as snt
from tensorflow.python import debug as tf_debug

# common part shared by two targets
class CommonPart(snt.AbstractModule):
    def __init__(self, name = "common_part"):
        super(CommonPart, self).__init__(name = name)
        with self._enter_variable_scope():
            self._conv = snt.Conv2D(4, [3, 3])

    def _build(self, inputs):
        return self._conv(inputs)

# one target with specific output 1
class Output1(snt.AbstractModule):
    def __init__(self, output_size, name = "output1"):
        super(Output1, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# another target with specific output 2
class Output2(snt.AbstractModule):
    def __init__(self, output_size, name = "output2"):
        super(Output2, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# t1 is input for target1
t1 = tf.truncated_normal([1, 5, 5, 1])

# t2 is input for target 2
t2 = tf.truncated_normal([1, 5, 5, 1])

# l1 is ground truth label for target 1
l1 = tf.constant([[1, 0]])

# l2 is ground truth label for target 2
l2 = tf.constant([[0, 1, 0, 0]])

opt = tf.train.AdamOptimizer(0.01)

# we create the model, the two-head monster
common_part = CommonPart()
output1 = Output1(2)
output2 = Output2(4)

# feed-forward computation
i1 = common_part(t1)
i2 = common_part(t2)

o1 = output1(snt.BatchFlatten()(i1))
o2 = output2(snt.BatchFlatten()(i2))

# losses for separated targets
l1 = tf.nn.softmax_cross_entropy_with_logits(labels = l1, logits = o1)
l2 = tf.nn.softmax_cross_entropy_with_logits(labels = l2, logits = o2)


TARGET1_VARIABLES = '_target1_variables_'
TARGET2_VARIABLES = '_target2_variables_'

def add_variable(var, collection_name, restore=True):
    if var not in tf.get_collection(collection_name):
      tf.add_to_collection(collection_name, var)

for var in common_part.get_variables():
    add_variable(var, TARGET1_VARIABLES)
    add_variable(var, TARGET2_VARIABLES)

for var in output1.get_variables():
    add_variable(var, TARGET1_VARIABLES)

for var in output2.get_variables():
    add_variable(var, TARGET2_VARIABLES)


# neither of the following computation will be succeded
# due to the incomplete information
g1 = opt.compute_gradients(l1, tf.get_collection(TARGET1_VARIABLES))
g2 = opt.compute_gradients(l2, tf.get_collection(TARGET2_VARIABLES))

g1_1 = [(grad, var) for grad, var in opt.compute_gradients(l1)
      if grad is not None]

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    # sess = tf_debug.LocalCLIDebugWrapperSession(sess)

    g1_val, g1_1_val = sess.run([g1, g1_1])

    g1_val = np.asarray(g1_val)
    g1_1_val = np.asarray(g1_1_val)

    print("g1_val -> ")
    print(g1_val)
    print("****************************************")
    print("g1_1_val -> ")
    print(g1_1_val)


```

I will keep it updating for the following part.

**Comment by mingyr** [comment]
@malcolmreynolds I also confirmed that if we add the respectively two losses together, it can also work. The problem here is, is there an easy way we can verify it is working in the way as intended? I mean for CommonPart module, two inputs contribute to the gradients, how could I verify that? I save the result into Matlab mat and import it into Matlab, however I lost my clue how to make comparison due to my limited knowledge of TensorFlow, So @malcolmreynolds do you have any idea? Thanks.

Please refer to the following code:

```
import numpy as np
import tensorflow as tf
import sonnet as snt
from tensorflow.python import debug as tf_debug

import scipy.io as sio

# common part shared by two targets
class CommonPart(snt.AbstractModule):
    def __init__(self, name = "common_part"):
        super(CommonPart, self).__init__(name = name)
        with self._enter_variable_scope():
            self._conv = snt.Conv2D(4, [3, 3])

    def _build(self, inputs):
        return self._conv(inputs)

# one target with specific output 1
class Output1(snt.AbstractModule):
    def __init__(self, output_size, name = "output1"):
        super(Output1, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# another target with specific output 2
class Output2(snt.AbstractModule):
    def __init__(self, output_size, name = "output2"):
        super(Output2, self).__init__(name = name)
        with self._enter_variable_scope():
            self._lin = snt.Linear(output_size)

    def _build(self, inputs):
        return self._lin(inputs)

# t1 is input for target1
t1 = tf.truncated_normal([1, 5, 5, 1])

# t2 is input for target 2
t2 = tf.truncated_normal([1, 5, 5, 1])

# l1 is ground truth label for target 1
l1 = tf.constant([[1, 0]])

# l2 is ground truth label for target 2
l2 = tf.constant([[0, 1, 0, 0]])

opt = tf.train.AdamOptimizer(0.01)

# we create the model, the two-head monster
common_part = CommonPart()
output1 = Output1(2)
output2 = Output2(4)

# feed-forward computation
i1 = common_part(t1)
i2 = common_part(t2)

o1 = output1(snt.BatchFlatten()(i1))
o2 = output2(snt.BatchFlatten()(i2))

# losses for separated targets
l1 = tf.nn.softmax_cross_entropy_with_logits(labels = l1, logits = o1)
l2 = tf.nn.softmax_cross_entropy_with_logits(labels = l2, logits = o2)

l = l1 + l2

g1 = [(grad, var) for grad, var in opt.compute_gradients(l1)
      if grad is not None]
g2 = [(grad, var) for grad, var in opt.compute_gradients(l2)
      if grad is not None]

g = opt.compute_gradients(l)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    g1_val, g2_val, g_val = sess.run([g1, g2, g])

    output = { 'g1': g1_val, 'g2': g2_val, 'g': g_val }

    sio.savemat("output.mat", output)

```

By the way, even if the filtered version is working:

```
g1 = [(grad, var) for grad, var in opt.compute_gradients(l1)
      if grad is not None]
g2 = [(grad, var) for grad, var in opt.compute_gradients(l2)
      if grad is not None]

```
However, is there a potential misalignment between variables? What I mean is, when we call opt.apply_gradients(g1) later, how it can anticipate the variables have been filtered in the previous compute_gradients call? Will such a mismatch cause partial variables updated in an incorrect way?

Further, if the above way (adding losses together then computing the gradients) is workable, then it is okay. Otherwise, it relies on the existence of misalignment or not. If there is misalignment, it will be a headache for multi-GPU training, since the stereotype average_gradients(tower_grads) will not work if we do not filtering. So this would be a dilemma.

Although to some extent get_variables can solve the problem, however my question here is why None be assigned as gradient for incomplete op node?  Why we can not have 0 substitute the None? What is the philosophy? So @malcolmreynolds can we point to TensorFlow team about this?

Welcome further discussion.

**Comment by malcolmreynolds** [comment]
@mingyr The choice of None for gradient computation instead of zero is explained here: https://github.com/tensorflow/tensorflow/issues/783 - there is clearly some debate over whether it's the right thing, but changing the default in TF would require a long deprecation cycle.

As to verifying whether it works correctly when combining the two losses, you can try building one graph which optimises the two losses separately, and retrieve the two gradient contributions to the common part, and then compare them to the combined gradient for the common part from the added-loss setup. Given the same input values, you should be able to add the two contributions from the first two and get the same gradients.

**Comment by mingyr** [comment]
@malcolmreynolds Thanks a lot for pointing out that. I also think tensorflow-ers have sufficient reason for doing so. I used to be a software programmer and fully understand that theoretic correctness doesn't imply practical feasibility.
Yes, you are quite right. I am too indulged into the complex way and forget it can be verified in some much simplified way. Thanks for pointing out that.
I will close this thread since if it didn't work in the way as expected, it should be a tensorflow issue instead sonnet.
