### ISSUE TITLE
Issue with snt.BatchApply in newer versions of TensorFlow

### ISSUE THREAD

**Issue by dbusbridge** [deepmind/sonnet#72]
I'm having an issue with a recent version of `TensorFlow` and the latest version
of `sonnet`. Specifically, I am building TensorFlow from source
(commit ref 318e071f7cb9fd51ddf0dda1e285e140167b4b56 compiled with cuda 9.0 and
cudnn 7.0.3), and I am also building Sonnet from source
(commit ref 7da90b8e63fb684b91a12e1e9a42999962804e3a, again with gpu options.
I have removed the dependency on tensorflow-gpu in order to not overwrite the
newer version of `TensorFlow` in the environment).

Specifically, there seems to be an issue with `BatchApply`. When running with
`TensorFlow 1.4` (which I compile under the same circumstances as the above 
version I mention), the following code behaves as expected:

```
>>> import sonnet as snt
... import tensorflow as tf
... 
... input = tf.placeholder(tf.float32, (None, 3, 5))
... 
... linear = snt.Linear(output_size=7)
... linear_batch = snt.BatchApply(linear)
... 
... output = linear_batch(input)
... 
>>> output
<tf.Tensor 'batch_apply/Reshape_1:0' shape=(?, 3, 7) dtype=float32>
```

When using the new version, I find the following behaviour:

```
>>> import sonnet as snt
... import tensorflow as tf
... 
... input = tf.placeholder(tf.float32, (None, 3, 5))
... 
... linear = snt.Linear(output_size=7)
... linear_batch = snt.BatchApply(linear)
... 
... output = linear_batch(input)
... 
Traceback (most recent call last):
  File "<input>", line 9, in <module>
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 275, in __call__
    outputs, this_name_scope = self._template(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 202, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/modules/basic.py", line 974, in _build
    flattened = nest.flatten_iterable([args, kwargs])
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/ops/nest.py", line 153, in flatten_iterable
    return list(_yield_flat_nest_from_iterable(structure))
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/ops/nest.py", line 103, in _yield_flat_nest_from_iterable
    for ni in _yield_flat_nest_from_iterable(n):
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/ops/nest.py", line 103, in _yield_flat_nest_from_iterable
    for ni in _yield_flat_nest_from_iterable(n):
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/ops/nest.py", line 101, in _yield_flat_nest_from_iterable
    for n in _yield_value_from_iterable(iterable):
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/ops/nest.py", line 96, in _yield_value_from_iterable
    for value in iterable:
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 377, in __iter__
    "`Tensor` objects are not iterable when eager execution is not "
TypeError: `Tensor` objects are not iterable when eager execution is not enabled. To iterate over this tensor use `tf.map_fn`.

originally defined at:
  File "<input>", line 7, in <module>
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/modules/basic.py", line 949, in __init__
    super(BatchApply, self).__init__(name=name)
  File "/home/dan/anaconda3/envs/env_crypto_master/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 174, in __init__
    custom_getter_=self._custom_getter)
```

So the introduction of eager execution seems to have altered some of the default
behaviours that `snt.BatchApply` depends on. I know it's stated that `sonnet` is
only advertised as being compatible with `TensorFlow 1.3`, so I know this may
be strictly out of scope, however, I thought it would be useful to raise the 
issue anyway to prepare for changes coming in `TensorFlow  1.5`.

Many thanks in advance!

**Comment by malcolmreynolds** [comment]
@dbusbridge Hi, thanks for the report. This is due to a recent change in whether Tensors are iterable or not, which isn't reflected in our current nest library. As you say, Sonnet is supported against one specific version of TF, and that won't necessarily be in sync with GitHub HEAD, or in this case the current stable version which arrived last week.

This is fixed internally and we should be pushing a new Sonnet version this week, I'll close this ticket once we've done that.

**Comment by dbusbridge** [comment]
Cool - thanks @malcolmreynolds!

**Comment by malcolmreynolds** [comment]
@dbusbridge If you reinstall Sonnet from either GitHub head, or pip, you should have a version that works with TF 1.4.0. Please let me know whether this is fixed for you!

**Comment by dbusbridge** [comment]
@malcolmreynolds That fixed it - thanks!
