### ISSUE TITLE
TypeError: 'TruncatedNormal' object is not iterable in providing vanilla RNN initializer in TensorFlow 1.3.0 or 1.4.0

### ISSUE THREAD

**Issue by dbusbridge** [deepmind/sonnet#74]
Hi,

I've been trying to provide an initializer to the VanillaRNN cell with the following code:

```
import numpy as np
import sonnet as snt
import tensorflow as tf

num_units = 16
batch_size = 17
sequence_length = 12
hidden_dim = 5

initalizers = {
  'hidden_to_hidden': tf.truncated_normal_initializer(stddev=1.0)}

cell = snt.VanillaRNN(
  hidden_size=num_units,
  initializers=initalizers)

# defining initial state
initial_state = cell.zero_state(batch_size, dtype=tf.float32)

# Define some inputs
inputs = tf.constant(
  value=np.ones(shape=[batch_size, sequence_length, hidden_dim]),
  dtype=tf.float32,
  name="inputs")

# Get the outputs and states
outputs, state = tf.nn.dynamic_rnn(
  cell=cell, inputs=inputs,
  initial_state=initial_state,
  dtype=tf.float32)
```

I get the following error when using either TensorFlow 1.3.0 or TensorFlow 1.4.0 and sonnet gpu 1.14

```
Traceback (most recent call last):
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-91e8f207af90>", line 5, in <module>
    dtype=tf.float32)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 614, in dynamic_rnn
    dtype=dtype)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 777, in _dynamic_rnn_loop
    swap_memory=swap_memory)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 762, in _time_step
    (output, new_state) = call_cell()
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 748, in <lambda>
    call_cell = lambda: cell(input_t, state)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 264, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 152, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/basic_rnn.py", line 141, in _build
    regularizers=self._regularizers.get("hidden_to_hidden"))
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/basic.py", line 186, in __init__
    initializers, self.possible_keys)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/util.py", line 149, in check_initializers
    if not set(initializers) <= keys:
TypeError: 'TruncatedNormal' object is not iterable

originally defined at:
  File "<ipython-input-3-869723f6b8d6>", line 6, in <module>
    initializers=initalizers)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/basic_rnn.py", line 99, in __init__
    super(VanillaRNN, self).__init__(name=name)
  File "/home/dan/anaconda3/envs/env_traderbot/lib/python3.6/site-packages/sonnet/python/modules/base.py", line 124, in __init__
    custom_getter_=self._custom_getter)
```

Thanks in advance!

Dan

**Comment by malcolmreynolds** [comment]
Hi @dbusbridge - the issue is the initializers dict. You need to provide a 2 level dict, as the weights you are trying to initialize are part of the `hidden_to_hidden` submodule. Try the following:

```
initalizers = {
    'hidden_to_hidden': {
        'w': tf.truncated_normal_initializer(stddev=1.0),
        'b': tf.zeros_initializer(),
    }
}
```

**Comment by malcolmreynolds** [comment]
Note - apologies, this is a pretty bad error message which doesn't help users - we will fix internally and have something which points out the exact mistake in the next version.

**Comment by dbusbridge** [comment]
Hi @malcolmreynolds thanks for clearing this up. In hindsight this makes total sense as the cell would have no idea which variable (w or b) was being initalized. Usefully, the following also works for specifying only w:
```
initalizers = {
  'hidden_to_hidden': {
    'w': tf.truncated_normal_initializer(stddev=1.0)
  }
}
```
Thanks again!
