### ISSUE TITLE
Build model with new TF dataset API

### ISSUE THREAD

**Issue by elmuz** [deepmind/sonnet#76]
I was trying to fine-tuning I3D network using the new TensorFlow dataset/iterator API and get rid of the _feed_dict_ approach. It seems the network cannot build since it can't understand input tensor dimensions. Here's some excerpt:
```
[...]
iterator = dataset.make_initializable_iterator()
next_input, next_label, _, _ = iterator.get_next()
with tf.variable_scope('RGB'):
  rgb_model = InceptionI3d(num_classes=10, spatial_squeeze=True, final_endpoint='Logits')
logits, _ = rgb_model(rgb_input, is_training=False, dropout_keep_prob=FLAGS.dropout_keep_prob)
[...]
```
this produces the following error:
```
File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/conv.py", line 2714, in _build
    "Number of input channels must be known at module build time")
sonnet.python.modules.base_errors.UnderspecifiedError: Number of input channels must be known at module build time
```

However, the tensor _next_input_ is correctly shaped in the form of [batch_size, frames, 224, 224, 3].
Can you see any error in my approach?
Thank you

**Comment by malcolmreynolds** [comment]
@elmuz Hi, could you post the full stack trace please, so I can see which Conv3D module invocation is causing the problem?

**Comment by elmuz** [comment]
Sure! Here's the full stack trace:

```
python3 Sandbox/dev/NTU-RGBD/test_input.py                                                                                   alessio@sonja
/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "Sandbox/dev/NTU-RGBD/test_input.py", line 124, in <module>
    test()
  File "Sandbox/dev/NTU-RGBD/test_input.py", line 71, in test
    logits, _ = rgb_model(next_element, is_training=False, dropout_keep_prob=FLAGS.dropout_keep_prob)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 264, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 152, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/alessio/Sandbox/dev/NTU-RGBD/i3d.py", line 170, in _build
    stride=[2, 2, 2], name=end_point)(net, is_training=is_training)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 264, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 152, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/home/alessio/Sandbox/dev/NTU-RGBD/i3d.py", line 65, in _build
    use_bias=self._use_bias)(inputs)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 264, in __call__
    outputs, subgraph_name_scope = self._template(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 268, in __call__
    result = self._call_func(args, kwargs, check_for_new_variables=False)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/template.py", line 217, in _call_func
    result = self._func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 152, in _build_wrapper
    output = self._build(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/conv.py", line 2714, in _build
    "Number of input channels must be known at module build time")
sonnet.python.modules.base_errors.UnderspecifiedError: Number of input channels must be known at module build time

originally defined at:
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/conv.py", line 2645, in __init__
    super(Conv3D, self).__init__(custom_getter=custom_getter, name=name)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 124, in __init__
    custom_getter_=self._custom_getter)


originally defined at:
  File "/home/alessio/Sandbox/dev/NTU-RGBD/i3d.py", line 43, in __init__
    super(Unit3D, self).__init__(name=name)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 124, in __init__
    custom_getter_=self._custom_getter)


originally defined at:
  File "Sandbox/dev/NTU-RGBD/test_input.py", line 70, in test
    rgb_model = InceptionI3d(num_classes=10, spatial_squeeze=True, final_endpoint='Logits')
  File "/home/alessio/Sandbox/dev/NTU-RGBD/i3d.py", line 139, in __init__
    super(InceptionI3d, self).__init__(name=name)
  File "/usr/local/lib/python3.5/dist-packages/sonnet/python/modules/base.py", line 124, in __init__
    custom_getter_=self._custom_getter)
```

**Comment by malcolmreynolds** [comment]
Thanks. In your code above, you say `next_input` is the [batch, 224, 224, 3], but it looks like you are connecting `rgb_input` to the Inception3D module. What size is that Tensor?

**Comment by elmuz** [comment]
I was wrong while writing this issue post. I edited the post accordingly. My input is 5D [batch, frames, height, width, channels].
Here's how I create the input:
```
dataset = tf.data.Dataset.from_tensor_slices((filenames, labels, lengths, num_frames))
  dataset = dataset.map(lambda filename, label, length, n_frames: tuple(tf.py_func(pack_frames, [filename, label, length, n_frames], [tf.uint8, label.dtype, length.dtype, n_frames.dtype])))
  dataset = dataset.map(preprocess)
```
from here Dataset is converted from "string" (like 'filenames' tensor) into [num_frames, height, width, channels] with alla augmentation needed. All others input slices are not touched.
```
  dataset = dataset.prefetch(50)
  dataset = dataset.batch(FLAGS.batch_size)
  iterator = dataset.make_initializable_iterator()
  next_input, next_label, _, _ = iterator.get_next()
```
Batch function add one dimension on top of input tensor. In fact if I print `tf.shape(next_element)` it shows up correctly.

**Comment by elmuz** [comment]
> it looks like you are connecting rgb_input to the Inception3D module. What size is that Tensor?
it was exactly the same. In fact the error is present by doing
```
  with tf.variable_scope('RGB'):
    rgb_model = InceptionI3d(num_classes=10, spatial_squeeze=True, final_endpoint='Logits')
  logits, _ = rgb_model(next_element, is_training=False, dropout_keep_prob=FLAGS.dropout_keep_prob)
```

**Comment by malcolmreynolds** [comment]
@elmuz could you provide a script that is a full reproduction for this issue? You don't need to send me your data, something which uses tf.data.Dataset.from_tensor_slices(tf.random(...)) to generate data of the right shape is sufficient. If you can upload that, plus the versions of TF and Sonnet that you are using, I can investigate further.

**Comment by elmuz** [comment]
I think the easiest way is to clone this repository: https://elmuz@bitbucket.org/elmuz/ntu-rgb.git which is more a toy example... The file you can launch is _test_input.py_, which relies on _input_data_NTURGBD.py_ for frame packeting and augmentation. I don't think you need any real data. Just give it fake, since it crash before anything else, when building the graph. There are probably more errors than the one I was talking about that I will find out as soon as I3D error will be solved.
Hope you can investigate a bit into it.
For the record, TF v. 1.4.1, Sonnet v. 1.14

**Comment by malcolmreynolds** [comment]
@elmuz I'm afraid I can't reproduce this. I made a fresh virtualenv and install TF and Sonnet with pip. I made the following changes to test_input.py, some of this is guesswork at what your actual data is like so please feel free to correct me. Alternatively, if you can provide something that matches your training_list.npy / testing_list.npy, such that I can clone the repo and run a single command to trigger the crash, then I can investigate more. Here's the relevant bit of code, with the "if False" block included so you can see where I started making modifications to the file. When I run this, the code constructs and connects the InceptionI3d model without problems, and hits the breakpoint at the bottom fine.

```python
  if False:
    # .npy data are in the form of [filename(string), label(int), video-length(int)]
    training_data = np.load(os.path.join(FLAGS.dataset_path, 'lists', 'training_list.npy'))
    testing_data = np.load(os.path.join(FLAGS.dataset_path, 'lists', 'testing_list.npy'))

    #augmentation = False

    filenames = tf.constant(training_data['file'])
    labels = tf.cast(tf.constant(training_data['label']), dtype=tf.int32)
    lengths = tf.constant(training_data['frames'])
    #num_frames = tf.constant(np.repeat(FLAGS.num_frames_per_clip, np.shape(training_data)), dtype=tf.int32)


    #dataset = tf.data.Dataset.from_tensor_slices((filenames, labels, lengths, num_frames))
    dataset = tf.data.Dataset.from_tensor_slices((filenames, labels, lengths))
    dataset = dataset.map(lambda filename, label, length: tuple(tf.py_func(pack_frames, [filename, label, length, FLAGS.num_frames_per_clip], [tf.uint8, label.dtype, length.dtype])))

  num_data = 1000
  length = 100
  height, width = 384, 512
  channels = 3
  fake_x = tf.cast(tf.zeros([num_data, length, height, width, channels]), tf.uint8)
  fake_y = tf.cast(tf.constant(np.random.rand(num_data) * 100), tf.int64)

  dataset = tf.data.Dataset.from_tensor_slices((fake_x, fake_y, tf.cast(fake_y, tf.int64)))
  dataset = dataset.map(preprocess)
  dataset = dataset.prefetch(50)
  dataset = dataset.batch(FLAGS.batch_size)

  iterator = dataset.make_initializable_iterator()
  next_element, next_label, _ = iterator.get_next()


  #rgb_input = tf.placeholder(tf.float32, shape=(None, FLAGS.num_frames_per_clip, FLAGS.crop_size, FLAGS.crop_size, 3), name='INPUT')
  #Y = tf.placeholder(tf.int64, [None])

  with tf.variable_scope('RGB'):
    rgb_model = InceptionI3d(num_classes=10, spatial_squeeze=True, final_endpoint='Logits')
  print('before rgb_model connection, next_element: %s' % next_element)
  logits, _ = rgb_model(next_element, is_training=False, dropout_keep_prob=FLAGS.dropout_keep_prob)
  print('after rgb_model connection')
  import pdb; pdb.set_trace()
```

Prints the following before a PDB prompt:

```shell
before rgb_model connection, next_element: Tensor("IteratorGetNext:0", shape=(?, ?, 224, 224, 3), dtype=float32)
after rgb_model connection
```

**Comment by elmuz** [comment]
[input.zip](https://github.com/deepmind/sonnet/files/1664759/input.zip)

You can try again:
1) Pull from the same .git above
2) Unzip this 'input.zip' somewhere... it contains two identical .npy files (train and test lists) and the frame of one single video sample (S001C001P001R001A001).
3) Numpy files are of the form:
[['S001C001P001R001A001', 1, 103],
['S001C001P001R001A001', 1, 103],
.... ] # this for 5000 rows, anyone pointing to the same video sample.
4) You can organize them something like:
/tmp/
   |_ frames
      |_ S001C001P001R001A001/
         |_ 0001.jpg
         |_ 0002.jpg
         |_ ...
   |_ lists
      |_ training_list.npy
      |_ testing_list.npy
5) Change 'input_data_NTURGBD.py' line 10 to '/tmp'
6) Change 'test_input.py' line 17 to '/tmp'
The other paths aren't involved for now...
Thank you in advance

**Comment by elmuz** [comment]
Thank you very much for your time. I really appreciated it!
