### ISSUE TITLE
Too limited documentation about DeepRNN

### ISSUE THREAD

**Issue by mingyr** [deepmind/sonnet#88]
Dear Deepminder,

Since there is too limited documentation of DeepRNN, could you please tell me what's wrong with my following way of using DeepRNN? I would guess it is a typical useage, however it always complains:

```
import tensorflow as tf
import sonnet as snt

class Cell(snt.RNNCore):
    def __init__(self, num_channels, spatial_size,
                 filter_size = 3, name = "cell"):
        """
        Args:
            num_channels: the number of output channels in the layer.
            spatial_size: spatial size of the input, [H, W]
            filter_size: the shape of the each convolution filter.
        """
        super(Cell, self).__init__(name = name)
        self._num_channels = num_channels
        self._spatial_size = spatial_size

        self._state_size = tf.TensorShape(spatial_size + [num_channels])
        self._output_size = tf.TensorShape(spatial_size + [num_channels])

        with self._enter_variable_scope():
            self._conv2d = snt.Conv2D(num_channels, [filter_size, filter_size])

    def inital_state(self, batch_size, spatial_size,
                     state_initializer = tf.zeros_initializer(), dtype = tf.float32):

        return state_initializer([batch_size] + self._spatial_size + [self._num_channels], dtype = dtype)

    def _build(self, inputs, state):
        """
        Basic recurrent network cell, with 2D convolution connections.

        Args:
            inputs: input Tensor, 4D, batch x height x width x channels.
            state: state Tensor, 4D, batch x height x width x channels.
        Returns:
            a tuple of tensors representing output and the new state.
        """

        inputs.get_shape().assert_has_rank(4)
        state.get_shape().assert_has_rank(4)

        inputs_h = tf.concat(axis = 3, values = [inputs, state])

        new_h = self._conv2d(inputs_h)

        return new_h, new_h

    @property
    def state_size(self):
        return self._state_size

    @property
    def output_size(self):
        return self._output_size

def test():
    import numpy as np
    t = tf.constant(np.ones([4, 8, 32, 32, 3]), tf.float32) # batch_size = 4
                                                            # sequence_length = 8
                                                            # spatial_size = [32, 32]
                                                            # num_channels = 3

    c1 = Cell(4, [32, 32])
    c2 = Cell(8, [32, 32])

    rnn = snt.DeepRNN([c1, c2], skip_connections = True, concat_final_output_if_skip = False)

    initial_state = tuple([c1.initial_state(4), c2.initial_state(4)])
    output_sequence, final_state = tf.nn.dynamic_rnn(rnn, rnn, initial_state = initial_state, time_major = False)

    config = tf.ConfigProto(log_device_placement = False)
    with tf.Session(config = config) as sess:
        sess.run([tf.global_variables_initializer(), tf.local_variables_initializer()])

        s, l = sess.run([output_sequence, final_state])
        print(s)

if __name__ == '__main__':
    test()

```

This is the output when I try to run the code:

```
(tensorflow)[yuming@cibci1 working-files]$ python deeprnn_test.py
WARNING:tensorflow:The `skip_connections` argument will be deprecated. Please use snt.SkipConnectionCore instead.
Traceback (most recent call last):
  File "deeprnn_test.py", line 80, in <module>
    test()
  File "deeprnn_test.py", line 67, in test
    rnn = snt.DeepRNN([c1, c2], skip_connections = True, concat_final_output_if_skip = False)
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/sonnet/python/modules/basic_rnn.py", line 289, in __init__
    self._check_cores_output_sizes()
  File "/home/yuming/tensorflow/lib/python2.7/site-packages/sonnet/python/modules/basic_rnn.py", line 307, in _check_cores_output_sizes
    "has size %s" % (first_core_list, i, core_list))
ValueError: The outputs of the provided cores are not able to be concatenated along the first feature dimension. Core 0 has size [32, 4], whereas Core 0 has size [32, 32, 8]
(tensorflow)[yuming@cibci1 working-files]$

```
I am grateful to your help since I think it is a typical user case.

**Comment by malcolmreynolds** [comment]
Hi @mingyr 

There are a few bugs in the error message here, apologies for the confusion. This will be fixed in the next version. The corrected error message should say:

```
ValueError: The outputs of the provided cores are not able to be concatenated along the first feature dimension. Core 0 has shape [32, 32, 4], whereas Core 1 has shape [32, 32, 8] - these must only differ in the first dimension
```

You've selected skip connections in DeepRNN so it's trying to concatenate the outputs from the two cores together to provide the final output. The sizes shown are the sizes without batch dimension, and the implementation concatenates on the first non-batch dimension. Therefore the rest of the shapes (in this case [32, 4] and [32, 8]) need to be the same, but they aren't.

If you disable skip connections this won't be a problem. If you definitely want skip connections, then presumably you are looking to concatenate on the channels dimension? You could either modify DeepRNN so that the concatenation dimension is customisable, or you could transpose your data into NCHW format, meaning you would have [4, 32, 32] and [8, 32, 32] which can be concatenated. Obviously this will require changes elsewhere too.

I hope this helps! Please let me know if the above isn't clear.

**Comment by mingyr** [comment]
Dear @malcolmreynolds 

I think you explained everything crystal clear. Sincerely appreciate it. 

Yes, you are quite right. I am looking to concatenate on the channels dimension. I am considering some dense recurrent structure to see whether there is performance improvement of the model I constructed.

BTW, probably Sonnet can consider provide such an interface since I might not be the only one who would like to try such a dense recurrent structure.
